theme: minima
title: Using Data to reshape the business
author: Michael Lee
email: mike_lee24@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Data provides integral insights for people and organizations to make evidence-based decisions and I believe this will be a cornerstone in business innovation for years to come. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
